<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DatasetData;

class DatasetDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Karang',
                'jumlah_nikah' => 40,
                'kantor' => 8,
                'luar_kantor' => 32,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Gedongombo',
                'jumlah_nikah' => 139,
                'kantor' => 32,
                'luar_kantor' => 107,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Jadi',
                'jumlah_nikah' => 61,
                'kantor' => 14,
                'luar_kantor' => 47,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Boto',
                'jumlah_nikah' => 17,
                'kantor' => 5,
                'luar_kantor' => 12,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Prunggahan Kulon',
                'jumlah_nikah' => 113,
                'kantor' => 30,
                'luar_kantor' => 83,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Tegalagung',
                'jumlah_nikah' => 18,
                'kantor' => 5,
                'luar_kantor' => 13,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Bektiharjo',
                'jumlah_nikah' => 91,
                'kantor' => 39,
                'luar_kantor' => 52,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 1,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Ngino',
                'jumlah_nikah' => 25,
                'kantor' => 5,
                'luar_kantor' => 20,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Prunggahan Wetan',
                'jumlah_nikah' => 11,
                'kantor' => 2,
                'luar_kantor' => 9,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Sambongrejo',
                'jumlah_nikah' => 21,
                'kantor' => 4,
                'luar_kantor' => 17,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Semanding',
                'jumlah_nikah' => 20,
                'kantor' => 3,
                'luar_kantor' => 17,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Bejagung',
                'jumlah_nikah' => 26,
                'kantor' => 3,
                'luar_kantor' => 23,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Penambangan',
                'jumlah_nikah' => 45,
                'kantor' => 13,
                'luar_kantor' => 32,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Genaharjo',
                'jumlah_nikah' => 37,
                'kantor' => 11,
                'luar_kantor' => 26,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Kowang',
                'jumlah_nikah' => 41,
                'kantor' => 10,
                'luar_kantor' => 31,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 1,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Tunah',
                'jumlah_nikah' => 55,
                'kantor' => 12,
                'luar_kantor' => 43,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Semanding',
                'desa' => 'Gesing',
                'jumlah_nikah' => 22,
                'kantor' => 7,
                'luar_kantor' => 15,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Karangasem',
                'jumlah_nikah' => 17,
                'kantor' => 2,
                'luar_kantor' => 15,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Socorejo',
                'jumlah_nikah' => 10,
                'kantor' => 2,
                'luar_kantor' => 8,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Temaji',
                'jumlah_nikah' => 21,
                'kantor' => 0,
                'luar_kantor' => 21,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Purworejo',
                'jumlah_nikah' => 12,
                'kantor' => 0,
                'luar_kantor' => 12,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Tasikharjo',
                'jumlah_nikah' => 11,
                'kantor' => 1,
                'luar_kantor' => 10,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Sumurgeneng',
                'jumlah_nikah' => 20,
                'kantor' => 0,
                'luar_kantor' => 20,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Suwalan',
                'jumlah_nikah' => 22,
                'kantor' => 4,
                'luar_kantor' => 18,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Remen',
                'jumlah_nikah' => 22,
                'kantor' => 1,
                'luar_kantor' => 21,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Beji',
                'jumlah_nikah' => 39,
                'kantor' => 7,
                'luar_kantor' => 32,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Wadung',
                'jumlah_nikah' => 16,
                'kantor' => 4,
                'luar_kantor' => 12,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Rawasan',
                'jumlah_nikah' => 23,
                'kantor' => 5,
                'luar_kantor' => 18,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Mentoso',
                'jumlah_nikah' => 26,
                'kantor' => 3,
                'luar_kantor' => 23,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Jenggolo',
                'jumlah_nikah' => 31,
                'kantor' => 6,
                'luar_kantor' => 25,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Kaliuntu',
                'jumlah_nikah' => 22,
                'kantor' => 3,
                'luar_kantor' => 19,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Sekardadi',
                'jumlah_nikah' => 11,
                'kantor' => 2,
                'luar_kantor' => 9,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Jenu',
                'jumlah_nikah' => 19,
                'kantor' => 3,
                'luar_kantor' => 16,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
            [
                'kecamatan' => 'Jenu',
                'desa' => 'Sugihwaras',
                'jumlah_nikah' => 43,
                'kantor' => 11,
                'luar_kantor' => 32,
                'nikah_campuran_laki_laki' => 0,
                'nikah_campuran_wanita' => 0,
                'jumlah_rujuk' => 0,
                'jumlah_isbat' => 0,
            ],
        ];

        foreach($data as $item) {
            DatasetData::create([
                'dataset_id' => 1,
                'tahun' => 2025,
                'data_json' => $item
            ]);
        }
    }
}
